### ISSUE TITLE
串口输入并不能使屏幕运动

### ISSUE THREAD

**Issue by zhenjunquan** [Sheep118/WouoUI-PageVersion#3]
您好 我在移植你的STM32 WouoUIPage项目的时候，串口输入并不能使屏幕运动，请问是什么原因呢，非常感谢

<img width="394" alt="pic" src="https://github.com/Sheep118/WouoUI-PageVersion/assets/92310189/581a738a-ed5a-4f20-94c0-4ddf1a8a2228">

**Comment by Sheep118** [comment]
你好，已经在B站看到你的问题了，有两种可能。
一个是，我在例程中使用的串口是串口2，引脚是PA2、PA3，你可能需要检查下有没有连接错。
另一个是，我在例程中使用串口的接收中断函数，数据是需要以"\r\n"结尾的(接收中断有检测这个，用来作为是否将数据放入buff的依据)，你可以检查下在使用电脑发送串口对应的数据时，是否有勾选发送新行这一项。
